version: "3.8"

services:
  db:
    image: postgres:16
    container_name: odoo18-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    container_name: odoo18-app
    user: "0:0"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command: >
      bash -c "
      sleep 5 &&
      if [ ! -f /var/lib/odoo/.created ]; then
        echo 'Creating initial Odoo database...' &&
        odoo -c /etc/odoo.conf -d auto_db --db_host=db --db_user=odoo --db_password=odoo --init base --without-demo=all --stop-after-init &&
        touch /var/lib/odoo/.created;
      fi &&
      echo 'Starting Odoo server...' &&
      odoo -c /etc/odoo.conf"
    volumes:
      - odoo18-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo.conf
    ports:
      - "8069:8069"

  nginx:
    image: nginx:alpine
    container_name: odoo18-nginx
    depends_on:
      - odoo
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx

volumes:
  odoo18-db-data:
  odoo18-web-data:
